services:
  auctioneer.api:
    image: auctioneer.api
    build:
      context: .
      dockerfile: src/Auctioneer.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - USER_SECRETS_ID=33ff7e54-390b-4fea-b6e9-d6b6ab651b2f
    ports:
      - "53961:80"
    volumes:
      - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID
      - $HOME/.microsoft/usersecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID

  auctioneer.emailservice:
    image: auctioneer.emailservice
    build:
      context: .
      dockerfile: src/Auctioneer.EmailService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - USER_SECRETS_ID=dotnet-Auctioneer.EmailService-3EC286A3-4D2D-4936-BB3D-3930F7551DA2
    ports:
      - "54011:80"
    volumes:
      - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID
      - $HOME/.microsoft/usersecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID

  auctioneer.notificationservice:
    image: auctioneer.notificationservice
    build:
      context: .
      dockerfile: src/Auctioneer.NotificationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - USER_SECRETS_ID=dotnet-Auctioneer.NotificationService-FDD3C79B-E224-4247-AF8D-7F2EA730417A
    ports:
      - "53811:80"
    volumes:
      - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID
      - $HOME/.microsoft/usersecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID
  
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.16.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data: